apiVersion: v2
name: todo-app
description: A Helm chart for deploying the Todo full-stack application
type: application

# Version is the chart version
version: 0.4.0

# AppVersion is the version of the application being deployed
appVersion: "1.0.0"