apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  databaseUrl: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.geminiApiKey }}
  geminiApiKey: {{ .Values.secrets.geminiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.betterAuthSecret }}
  betterAuthSecret: {{ .Values.secrets.betterAuthSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientId }}
  googleClientId: {{ .Values.secrets.googleClientId | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientSecret }}
  googleClientSecret: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.accessTokenExpireMinutes }}
  accessTokenExpireMinutes: {{ .Values.secrets.accessTokenExpireMinutes | quote }}
  {{- end }}
  {{- if .Values.secrets.refreshTokenExpireDays }}
  refreshTokenExpireDays: {{ .Values.secrets.refreshTokenExpireDays | quote }}
  {{- end }}
  {{- if .Values.secrets.googleRedirectUri }}
  googleRedirectUri: {{ .Values.secrets.googleRedirectUri | quote }}
  {{- end }}